# Generated by Django 4.1.5 on 2023-02-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='city',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='plot',
            name='plot_id',
            field=models.CharField(max_length=40, unique=True, verbose_name='Plot ID'),
        ),
    ]
