# Generated by Django 4.1.5 on 2023-02-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_management', '0002_plot_city_alter_plot_plot_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='plot_address',
            field=models.CharField(max_length=50, verbose_name='Plot Address'),
        ),
        migrations.AlterField(
            model_name='plot',
            name='plot_name',
            field=models.CharField(max_length=40, verbose_name='Plot Name'),
        ),
    ]
