# Generated by Django 4.1.5 on 2023-02-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_management', '0003_alter_plot_plot_address_alter_plot_plot_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='plot_address',
            field=models.CharField(max_length=300, verbose_name='Plot Address'),
        ),
    ]
