# Generated by Django 4.1.5 on 2023-01-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0002_carslot_is_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='carslot',
            name='created_at',
            field=models.DateField(auto_created=True, blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carslot',
            name='updated_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='created_at',
            field=models.DateField(auto_created=True, blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
