# Generated by Django 4.1.5 on 2023-01-19 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0003_carslot_created_at_carslot_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carslot',
            name='from_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='From Time'),
        ),
        migrations.AddField(
            model_name='carslot',
            name='sequence_number',
            field=models.PositiveIntegerField(default=0, verbose_name='Slot Number'),
        ),
        migrations.AddField(
            model_name='carslot',
            name='slot_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Slot ID'),
        ),
        migrations.AddField(
            model_name='carslot',
            name='to_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='To Time'),
        ),
    ]
