# Generated by Django 4.1.5 on 2023-01-19 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0004_carslot_from_time_carslot_sequence_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carslot',
            name='slot_id',
            field=models.CharField(default=1, max_length=200, unique=True, verbose_name='Slot ID'),
            preserve_default=False,
        ),
    ]
