# Generated by Django 4.1.5 on 2023-01-19 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0006_remove_carslot_created_at_remove_carslot_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carslot',
            name='slot_date',
            field=models.DateField(default='2023-01-19', verbose_name='Slot Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carslot',
            name='from_time',
            field=models.TimeField(blank=True, null=True, verbose_name='From Time'),
        ),
        migrations.AlterField(
            model_name='carslot',
            name='to_time',
            field=models.TimeField(blank=True, null=True, verbose_name='To Time'),
        ),
    ]
