# Generated by Django 4.1.5 on 2023-01-24 18:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0007_carslot_slot_date_alter_carslot_from_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slot_payments', to='parking_app.carslot'),
        ),
        migrations.CreateModel(
            name='SlotTimeWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('slot_start_time', models.TimeField(blank=True, null=True, verbose_name='Slot Start Time')),
                ('slot_end_time', models.TimeField(blank=True, null=True, verbose_name='Slot End Time')),
                ('slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slot_windows', to='parking_app.carslot')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
