# Generated by Django 4.1.5 on 2023-01-25 04:56

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0008_alter_payment_slot_slottimewindow'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('slot_id', models.CharField(max_length=200, unique=True, verbose_name='Slot ID')),
                ('is_booked', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='carslot',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carslot',
            name='payment_method',
            field=models.CharField(choices=[('PREPAID', 'Prepaid'), ('CASH', 'Cash'), ('CHQ', 'Cheque'), ('CREDITCARD', 'Credit Card')], default='CASH', max_length=25, verbose_name='Payment Method'),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
