# Generated by Django 4.1.5 on 2023-01-28 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0010_remove_slottimewindow_slot_fixedslot_from_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carslot',
            name='name',
        ),
        migrations.AlterField(
            model_name='carslot',
            name='slot_id',
            field=models.CharField(max_length=200, verbose_name='Slot ID'),
        ),
    ]
