# Generated by Django 4.1.5 on 2023-01-30 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0011_remove_carslot_name_alter_carslot_slot_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SlotTimeWindow',
        ),
    ]
