# Generated by Django 4.1.5 on 2023-02-03 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parking_app', '0012_delete_slottimewindow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('slot_date', models.DateField(verbose_name='Slot Date')),
                ('slot_id', models.CharField(max_length=200, verbose_name='Slot ID')),
                ('sequence_number', models.PositiveIntegerField(default=0, verbose_name='Slot Number')),
                ('is_booked', models.BooleanField(default=False)),
                ('payment_method', models.CharField(choices=[('PREPAID', 'Prepaid'), ('CASH', 'Cash'), ('CHQ', 'Cheque'), ('CREDITCARD', 'Credit Card')], default='CASH', max_length=25, verbose_name='Payment Method')),
                ('slot_status', models.CharField(choices=[('EMPTY_BOOKED_SLOT', 'Empty Slot'), ('PARTIAL_BOOKED_SLOT', 'Partial Slot'), ('FULL_BOOKED_SLOT', 'Full Slot')], default='EMPTY_BOOKED_SLOT', max_length=25, verbose_name='Slot Status')),
                ('amount', models.PositiveIntegerField(default=0)),
                ('from_time', models.TimeField(blank=True, null=True, verbose_name='From Time')),
                ('to_time', models.TimeField(blank=True, null=True, verbose_name='To Time')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='CarSlot',
        ),
    ]
