# Generated by Django 4.1.5 on 2023-02-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0013_slot_delete_carslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='reference_number',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Reference Number'),
        ),
        migrations.AddField(
            model_name='slot',
            name='vehicle_plat_no',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Vehicle No'),
        ),
        migrations.AddField(
            model_name='slot',
            name='vehicle_type',
            field=models.CharField(choices=[('TWO_WHEELER', '2 Wheeler'), ('THREE_WHEELER', '3 Wheeler'), ('FOUR_WHEELER', '4 wheeler'), ('SIX_WHEELER', '6 wheeler'), ('EIGHT_WHEELER', '8 wheeler'), ('OTHER', '6 wheeler')], default='FOUR_WHEELER', max_length=30, verbose_name='Vehicle Type'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='slot_id',
            field=models.CharField(max_length=10, verbose_name='Slot ID'),
        ),
    ]
