# Generated by Django 4.1.5 on 2023-02-06 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_management', '0001_initial'),
        ('parking_app', '0017_alter_slot_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedslot',
            name='plot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plot_slots', to='admin_management.plot'),
        ),
    ]
