# Generated by Django 4.1.5 on 2023-02-11 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_management', '0003_alter_plot_plot_address_alter_plot_plot_name'),
        ('parking_app', '0018_fixedslot_plot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='sequence_number',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='slot_id',
        ),
        migrations.AddField(
            model_name='slot',
            name='plot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plot_user_slots', to='admin_management.plot'),
        ),
        migrations.AddField(
            model_name='slot',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fixed_user_slots', to='parking_app.fixedslot', verbose_name='Fixed Slot'),
        ),
    ]
